# Generated by Django 2.2.6 on 2019-10-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nr_cc', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
            ],
        ),
    ]
