# Generated by Django 2.2.6 on 2019-10-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distrito',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nr_cc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
