# Generated by Django 2.2.6 on 2019-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0002_auto_20191022_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
