# Generated by Django 2.2.6 on 2019-10-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0003_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='utilizador',
        ),
    ]
