# Generated by Django 2.2.6 on 2019-10-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0004_auto_20191022_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizador',
            old_name='nr_cc',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='distrito',
            new_name='n_distrito',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='email',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='password',
            new_name='ocupacao',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='username',
            new_name='palavrapasse',
        ),
    ]
