# Generated by Django 2.2.6 on 2019-10-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0005_auto_20191022_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='n_distrito',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='ocupacao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='palavrapasse',
            field=models.CharField(max_length=50),
        ),
    ]
