# Generated by Django 2.2.6 on 2019-10-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0006_auto_20191022_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_distrito', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='n_distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinistralidade.distrito'),
        ),
    ]
