# Generated by Django 2.2.6 on 2019-10-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0007_auto_20191025_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distrito',
            old_name='n_distrito',
            new_name='nome',
        ),
    ]
