# Generated by Django 2.2.6 on 2019-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0008_auto_20191025_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='n_distrito',
            field=models.CharField(max_length=150),
        ),
    ]
