# Generated by Django 2.2.6 on 2019-10-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0009_auto_20191025_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='id',
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nome',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='n_distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinistralidade.distrito'),
        ),
    ]
