# Generated by Django 2.2.6 on 2019-10-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0011_auto_20191025_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='n_distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinistralidade.distrito'),
        ),
    ]
