# Generated by Django 2.2.6 on 2019-10-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0013_auto_20191025_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='concelho',
            fields=[
                ('nome', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('n_Distrito', models.CharField(max_length=150)),
            ],
        ),
    ]
