# Generated by Django 2.2.6 on 2019-10-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0014_concelho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concelho',
            name='n_Distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinistralidade.distrito'),
        ),
    ]
