# Generated by Django 2.2.6 on 2019-10-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0015_auto_20191025_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concelho',
            name='n_Distrito',
        ),
        migrations.AddField(
            model_name='concelho',
            name='n_distrito',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
