# Generated by Django 2.2.6 on 2019-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0016_auto_20191025_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='acidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concelho', models.CharField(max_length=150)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('mortos', models.IntegerField()),
                ('feridosg', models.IntegerField()),
                ('via', models.CharField(max_length=150)),
                ('km', models.CharField(max_length=150)),
                ('natureza', models.CharField(max_length=150)),
            ],
        ),
    ]
