# Generated by Django 2.2.6 on 2019-10-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0017_acidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidente',
            name='datahora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
