# Generated by Django 2.2.6 on 2019-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0018_auto_20191025_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidente',
            name='datahora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
