# Generated by Django 2.2.6 on 2019-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0019_auto_20191025_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='historico',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('cc_user', models.IntegerField()),
                ('Id_acidente', models.IntegerField()),
            ],
        ),
    ]
