# Generated by Django 2.2.6 on 2019-10-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0020_historico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='Id',
            new_name='id',
        ),
    ]
