# Generated by Django 2.2.6 on 2019-10-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0021_auto_20191027_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='Id_acidente',
            new_name='id_acidente',
        ),
    ]
