# Generated by Django 2.2.6 on 2019-10-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0022_auto_20191027_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
