# Generated by Django 2.2.6 on 2019-10-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0024_auto_20191029_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
