# Generated by Django 2.2.6 on 2019-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistralidade', '0025_auto_20191029_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
